### ISSUE TITLE
"Show Build" fails

### ISSUE THREAD

**Issue by EivindArvesen** [Section214/ST3-Travis-CI#2]
When I select `Travis CI: Show Build` in the quick panel nothing happens, and the following appears in my console:

``` python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "travis-ci in /Users/Eivind/Library/Application Support/Sublime Text 3/Installed Packages/Travis-CI.sublime-package", line 225, in run
UnboundLocalError: local variable 'repo' referenced before assignment
```

**Comment by evertiro** [comment]
Does the status bar display correctly? (ie, is the plugin working at all for you?) I haven't been able to reproduce this error.

**Comment by EivindArvesen** [comment]
Nope, my status bar shows nothing related to Travis-CI.
I tried enabling debug via user-settings, but the only debug output I saw was

``` python
WARNING Could not import subprocess32 module, falling back to subprocess module
```

**Comment by evertiro** [comment]
First thing... can you make sure you're running the latest version (1.0.4)? If you are... we'll have to dig in a bit!

**Comment by EivindArvesen** [comment]
Sure! According to package control, I'm on 1.0.4.

**Comment by evertiro** [comment]
Ok. From the traceback you posted, I'm guessing you're on Mac... can you tell me what version?

**Comment by EivindArvesen** [comment]
The OS version is "El Capitan" (10.11.1).

**Comment by evertiro** [comment]
That's strange... that's the ONE OS I'm confident it works on... That's what I'm running! The warning you posted yesterday isn't an error... just means that it's running using a fallback module. Doesn't effect functionality.

The traceback is a legitimate bug... I'm not properly handling one possible situation, but the only reason that should happen is if the directory that the current file is in isn't a git repo... in which case Travis wouldn't do anything anyway.

Are you willing to install a development branch for some debugging?

**Comment by EivindArvesen** [comment]
Seems odd - I've tried opening several projects, and folders that all contain git-repositories.

Sure, I'd be willing to do that!

**Comment by Kristinita** [comment]
@ghost1227, I reproduce the problem. I open, for example, `.travis.yml` file of my project, integrate with Travis CI → I run command `travis_show_build` → I get stack trace.

```python
command: travis_show_build
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 797, in run_
    return self.run()
  File "travis-ci in D:\Sublime Text 3 x64\Data\Installed Packages\Travis-CI.sublime-package", line 225, in run
UnboundLocalError: local variable 'repo' referenced before assignment
```

### Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126


Thanks.
